### ISSUE TITLE
BOGO Sort

### ISSUE THREAD

**Issue by l0g1c-80m8** [fleece30/leetcode-practice#1]
Can you please add the algorithm of BOGO sort?
It is the most useful algorithm you'll ever come across for sorting [💥](https://www.geeksforgeeks.org/bogosort-permutation-sort/).

(Click on the emoji to check the algorithm out)

**Comment by l0g1c-80m8** [comment]
Here's a python solution:

```
from random import shuffle

def bogosort(data):
    while not all(a <= b for a, b in zip(data, data[1: ])):
        shuffle(data)
    return data
```

**Comment by TheDescendant39** [comment]
Agree with @l0g1c-80m8 here. 🚀🚀🚀

**Comment by Kyrt-del** [comment]
🚀🚀🚀

**Comment by fleece30** [comment]
🫡

**Comment by kausthub13** [comment]
🚀🚀🚀🚀🚀🚀
